### ISSUE TITLE
real time anomaly detection 

### ISSUE THREAD

**Issue by FeizNouri** [lsanomaly/lsanomaly#1]
Hi 
i'm working on timeseries anomaly detection, can lsanomaly work in real time?

**Comment by dmwesterhoff** [comment]
Yep, you can almost definitely get something running pseudo real time. I would say in general it probably depends on a few factors:
- Time to refresh / update cycles
- Amount of data
- How close to real time you need it

Those are all pretty closely related variables when your operating in real time and each one is going to have impact on the performance. I might be able to give you some guidance if you define the problem and your requirements. You can probably do some benchmarking on how long each fit/predict cycle will take and that will give you an idea of how close to *true* real-time you can get it.

**Comment by FeizNouri** [comment]
Hi 
thanks for replying :) 
i need to run the anomaly not exactly in real time but like in every 1 min freq.
i have data coming every 1 min from an influxDB database, these values are energy consumption in "real time", the idea is to train on a perfect week or two (with no anomalies) and i want to do the test on the "real time"... i successfully run Lsanomaly, training on one week or month and test on a whole new day, now i need to test on real time so that if there is an anomaly in the energy consumption i can get an alert.
i did some training and testing on different databases and for a typical one the fit takes 0.00010871 sec and predicting takes 0.00010800 sec. 
thanks for your help.
